apiVersion: v1
kind: ConfigMap
metadata:
  name: moving-shapes-colors
  CIRCLE_COLOR: "pink"
  OVAL_COLOR: "lightgreen"
  SQUARE_COLOR: "orange"
  TRIANGLE_COLOR: "white"   # use white to get a Degraded message in ArgoCD
  RECTANGLE_COLOR: "blue" 
